FROM ajoergensen/baseimage-ubuntu
ENV PHP_VERSION=5.6

COPY build /build

RUN \
        /build/setup.sh && \
	rm -rf /build

COPY root/ /

RUN \
	chmod -v +x /etc/my_init.d/*.sh /etc/service/*/run

EXPOSE 80

VOLUME /var/www

